version: '3.9'

services:

  keycloak1:
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    container_name: keycloak1
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin2=disabled
    volumes:
     - ./keycloak-custom-authenticator/target/keycloak-lab-authenticator-1.0-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-lab-authenticator-1.0-SNAPSHOT.jar
     - ./keycloak-rest-repo/target/keycloak-lab-repo-1.0.0-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-lab-repo-1.0.0-SNAPSHOT.jar
     
    ports:
      - 8080:8080
    
  mmock:
      image: jordimartin/mmock
      container_name: mmock
      restart: always
      volumes:
        - ./mmock/:/config/
      ports:
        - 8082:8082
        - 8083:8083
      